# Generated by Django 5.2 on 2025-07-25 07:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_category', models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form')),
                ('coffee_type', models.CharField(choices=[('ARABICA', 'Arabica'), ('ROBUSTA', 'Robusta'), ('BLEND', 'Blend')], default='ARABICA', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Coffee Inventory',
                'ordering': ['coffee_category', 'coffee_type'],
                'unique_together': {('coffee_category', 'coffee_type')},
            },
        ),
        migrations.CreateModel(
            name='CoffeePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_category', models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form')),
                ('coffee_type', models.CharField(choices=[('AR', 'Arabica'), ('RB', 'Robusta')], default='AR', max_length=2)),
                ('quantity', models.DecimalField(decimal_places=0, help_text='Weight in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bags', models.PositiveIntegerField(default=0, help_text='Number of bags (if applicable)', validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_price', models.DecimalField(decimal_places=0, default=0, help_text='Reference price per kilogram', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('D', 'Paid'), ('T', 'Partial')], default='P', max_length=1, verbose_name='Payment Status')),
                ('assessment', models.BooleanField(default=False, verbose_name='Quality Assessment')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coffee Purchase',
                'verbose_name_plural': 'Coffee Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_content', models.FloatField(blank=True, null=True)),
                ('group1_defects', models.FloatField(blank=True, null=True)),
                ('group2_defects', models.FloatField(blank=True, null=True)),
                ('below_screen_12', models.FloatField(blank=True, null=True)),
                ('outturn', models.FloatField(blank=True, null=True)),
                ('actual_outturn', models.FloatField(blank=True, null=True)),
                ('pods', models.FloatField(blank=True, null=True)),
                ('husks', models.FloatField(blank=True, null=True)),
                ('stones', models.FloatField(blank=True, null=True)),
                ('discretion', models.FloatField(default=0)),
                ('coffee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quality_assessment', to='app.coffeepurchase')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('coffee_category', models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form')),
                ('coffee_type', models.CharField(choices=[('AR', 'Arabica'), ('RB', 'Robusta')], default='AR', max_length=2)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coffee Sale',
                'verbose_name_plural': 'Coffee Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MillingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('hulled_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('milling_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=5)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('X', 'Cancelled')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milling_processes', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MillingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='app.customeraccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('milling_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.millingprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coffee Supplier',
                'verbose_name_plural': 'Coffee Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='app.supplier'),
        ),
        migrations.AddConstraint(
            model_name='coffeepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0.01)), name='quantity_gte_001'),
        ),
    ]
