# Generated by Django 5.1.1 on 2025-04-04 12:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(editable=False, help_text='Auto-generated customer ID (format: GPC001)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeMilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_coffee_weight', models.DecimalField(decimal_places=2, help_text='Weight of coffee before milling (Kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('hulled_coffee_weight', models.DecimalField(decimal_places=2, help_text='Weight of coffee after milling (Kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('coffee_type', models.CharField(choices=[('arabica', 'Arabica'), ('robusta', 'Robusta')], default='arabica', help_text='Type of coffee being milled', max_length=10)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, help_text='Moisture content of the coffee (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('milling_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when milling occurred')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, help_text='Cost per Kg for milling', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000)])),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated total milling cost', max_digits=10)),
                ('milling_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the milling process', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this milling', null=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when record was created')),
                ('registered_by', models.ForeignKey(help_text='Staff member who recorded this milling', on_delete=django.db.models.deletion.CASCADE, related_name='milling', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who brought the coffee', on_delete=django.db.models.deletion.CASCADE, related_name='milling_records', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.customer')),
                ('milling_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.coffeemilling')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
