# Generated by Django 5.2 on 2025-07-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='actual_outturn',
            new_name='fm',
        ),
    ]
