# Generated by Django 5.2 on 2025-04-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeemilling',
            name='coffee_type',
        ),
        migrations.RemoveField(
            model_name='coffeemilling',
            name='moisture_content',
        ),
        migrations.RemoveField(
            model_name='coffeemilling',
            name='raw_coffee_weight',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
