# Generated by Django 5.2 on 2025-06-23 09:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_coffeepurchase_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepurchase',
            name='coffee_category',
            field=models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form'),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='coffee_type',
            field=models.CharField(choices=[('AR', 'Arabica'), ('RB', 'Robusta')], default='AR', max_length=2),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, help_text='Weight in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='recorded_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=1, help_text='Price per kilogram', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='coffeepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0.01)), name='quantity_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='coffeepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0.01)), name='unit_price_gte_001'),
        ),
    ]
