# Generated by Django 5.2 on 2025-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_millingprocess_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millingprocess',
            name='milling_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=150.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='millingprocess',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('C', 'Completed'), ('X', 'Cancelled')], default='C', max_length=1, null=True),
        ),
    ]
