# Generated by Django 5.2 on 2025-06-24 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coffeepurchase_coffee_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millingprocess',
            name='initial_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='millingprocess',
            name='milling_rate',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=5),
        ),
    ]
