# Generated by Django 5.2 on 2025-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_millingprocess_initial_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millingprocess',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('X', 'Cancelled')], default='C', max_length=1),
        ),
    ]
