# Generated by Django 5.2 on 2025-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_millingprocess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeesale',
            name='customer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
