# Generated by Django 5.2 on 2025-06-24 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_coffeesale_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('ARABICA', 'Arabica'), ('ROBUSTA', 'Robusta'), ('BLEND', 'Blend')], default='ARABICA', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Coffee Inventory',
                'ordering': ['coffee_type'],
                'unique_together': {('coffee_type',)},
            },
        ),
    ]
