# Generated by Django 5.2 on 2025-06-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coffeeinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeesale',
            name='sale_type',
        ),
        migrations.AddField(
            model_name='coffeesale',
            name='coffee_category',
            field=models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form'),
        ),
        migrations.AddField(
            model_name='coffeesale',
            name='coffee_type',
            field=models.CharField(choices=[('AR', 'Arabica'), ('RB', 'Robusta')], default='AR', max_length=2),
        ),
        migrations.AddField(
            model_name='coffeesale',
            name='customer_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coffeesale',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
