# Generated by Django 5.2 on 2025-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_transaction_millingtransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeeinventory',
            options={'ordering': ['coffee_category', 'coffee_type'], 'verbose_name_plural': 'Coffee Inventory'},
        ),
        migrations.AlterUniqueTogether(
            name='coffeeinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coffeeinventory',
            name='coffee_category',
            field=models.CharField(blank=True, choices=[('GR', 'Green Coffee'), ('PA', 'Parchment Coffee'), ('KB', 'Kiboko Coffee')], max_length=2, verbose_name='Coffee Form'),
        ),
        migrations.AlterUniqueTogether(
            name='coffeeinventory',
            unique_together={('coffee_category', 'coffee_type')},
        ),
    ]
